name: payup
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  font_awesome_flutter: ^8.10.1
  sign_button: ^1.0.0
  google_fonts:
  flutter_screenutil:
  flutter_launcher_icons: ^0.8.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: KumbhSans
      fonts:
        - asset: fonts/KumbhSans-Bold.ttf
    - family: Bambino
      fonts:
        - asset: fonts/Bambino-Bold.ttf
